// This file is generated by `sprites/imgToHex`, it shouldn't be modified for long term changes.

//Those variables are from the libImages.so lib.
extern unsigned char img_deadOther_deadOther01_bmp;
extern unsigned int  img_deadOther_deadOther01_bmp_len;

extern unsigned char img_dog_dog01_bmp;
extern unsigned int  img_dog_dog01_bmp_len;

extern unsigned char img_dog_dog02_bmp;
extern unsigned int  img_dog_dog02_bmp_len;

extern unsigned char img_dog_dog03_bmp;
extern unsigned int  img_dog_dog03_bmp_len;

extern unsigned char img_dog_dog04_bmp;
extern unsigned int  img_dog_dog04_bmp_len;

extern unsigned char img_dog_dog05_bmp;
extern unsigned int  img_dog_dog05_bmp_len;

extern unsigned char img_cat_cat01_bmp;
extern unsigned int  img_cat_cat01_bmp_len;

extern unsigned char img_cat_cat02_bmp;
extern unsigned int  img_cat_cat02_bmp_len;

extern unsigned char img_cat_cat03_bmp;
extern unsigned int  img_cat_cat03_bmp_len;

extern unsigned char img_cat_cat04_bmp;
extern unsigned int  img_cat_cat04_bmp_len;

extern unsigned char img_cat_cat05_bmp;
extern unsigned int  img_cat_cat05_bmp_len;

extern unsigned char img_cat_cat06_bmp;
extern unsigned int  img_cat_cat06_bmp_len;

extern unsigned char img_cat_cat07_bmp;
extern unsigned int  img_cat_cat07_bmp_len;

extern unsigned char img_cat_cat08_bmp;
extern unsigned int  img_cat_cat08_bmp_len;

extern unsigned char img_cat_cat09_bmp;
extern unsigned int  img_cat_cat09_bmp_len;

extern unsigned char img_cat_cat10_bmp;
extern unsigned int  img_cat_cat10_bmp_len;

extern unsigned char img_other_other01_bmp;
extern unsigned int  img_other_other01_bmp_len;

extern unsigned char img_deadCat_deadcat1_bmp;
extern unsigned int  img_deadCat_deadcat1_bmp_len;

extern unsigned char img_deadCat_deadcat2_bmp;
extern unsigned int  img_deadCat_deadcat2_bmp_len;

extern unsigned char img_deadCat_deadcat3_bmp;
extern unsigned int  img_deadCat_deadcat3_bmp_len;



/** An array containing pointers to all image dumps */
inline const unsigned char* allDump[] = {
	&img_deadOther_deadOther01_bmp,
	&img_dog_dog01_bmp,
	&img_dog_dog02_bmp,
	&img_dog_dog03_bmp,
	&img_dog_dog04_bmp,
	&img_dog_dog05_bmp,
	&img_cat_cat01_bmp,
	&img_cat_cat02_bmp,
	&img_cat_cat03_bmp,
	&img_cat_cat04_bmp,
	&img_cat_cat05_bmp,
	&img_cat_cat06_bmp,
	&img_cat_cat07_bmp,
	&img_cat_cat08_bmp,
	&img_cat_cat09_bmp,
	&img_cat_cat10_bmp,
	&img_other_other01_bmp,
	&img_deadCat_deadcat1_bmp,
	&img_deadCat_deadcat2_bmp,
	&img_deadCat_deadcat3_bmp,
};
/** The size of `allDump` */
inline constexpr size_t allDumpSize = 20;


/** An array containing the length of all image dumps (sorted in the same order as `allDump`) */
inline const unsigned int allDumpLen[] = {
	img_deadOther_deadOther01_bmp_len,
	img_dog_dog01_bmp_len,
	img_dog_dog02_bmp_len,
	img_dog_dog03_bmp_len,
	img_dog_dog04_bmp_len,
	img_dog_dog05_bmp_len,
	img_cat_cat01_bmp_len,
	img_cat_cat02_bmp_len,
	img_cat_cat03_bmp_len,
	img_cat_cat04_bmp_len,
	img_cat_cat05_bmp_len,
	img_cat_cat06_bmp_len,
	img_cat_cat07_bmp_len,
	img_cat_cat08_bmp_len,
	img_cat_cat09_bmp_len,
	img_cat_cat10_bmp_len,
	img_other_other01_bmp_len,
	img_deadCat_deadcat1_bmp_len,
	img_deadCat_deadcat2_bmp_len,
	img_deadCat_deadcat3_bmp_len,
};
/** The size of `allDumpLen` */
inline constexpr size_t allDumpLenSize = 20;


/** An array containing all the names of folders. */
inline const char* allNames[] = {
	"deadOther",
	"dog",
	"cat",
	"other",
	"deadCat",
};
inline constexpr size_t allNamesSize = 5;


/** How many deadCat sprites there are in `allDump`. */
inline constexpr uint8_t deadCatCount	= 3;

/** How many dog sprites there are in `allDump`. */
inline constexpr uint8_t dogCount	= 5;

/** How many animal sprites there are in `allDump`. */
inline constexpr uint8_t otherCount	= 1;

/** How many deadOther sprites there are in `allDump`. */
inline constexpr uint8_t deadOtherCount	= 1;

/** How many cat sprites there are in `allDump`. */
inline constexpr uint8_t catCount	= 10;

/** An array containing all {class}Count, should be used with `allNames`. */
inline size_t countList[] = {
	deadOtherCount,
	dogCount,
	catCount,
	otherCount,
	deadCatCount,
};
inline constexpr size_t countListSize = 5;

